// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission12.Models;

namespace Mission12.Migrations
{
    [DbContext(typeof(AptContext))]
    [Migration("20220324034325_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission12.Models.Appointment", b =>
                {
                    b.Property<int>("AptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Booked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AptId");

                    b.ToTable("Appointment");

                    b.HasData(
                        new
                        {
                            AptId = 1,
                            Booked = false,
                            Day = "Monday",
                            Time = "8:00 AM"
                        },
                        new
                        {
                            AptId = 2,
                            Booked = false,
                            Day = "Monday",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            AptId = 3,
                            Booked = false,
                            Day = "Monday",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            AptId = 4,
                            Booked = false,
                            Day = "Monday",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            AptId = 5,
                            Booked = false,
                            Day = "Monday",
                            Time = "12:00 PM"
                        },
                        new
                        {
                            AptId = 6,
                            Booked = false,
                            Day = "Monday",
                            Time = "1:00 PM"
                        },
                        new
                        {
                            AptId = 7,
                            Booked = false,
                            Day = "Monday",
                            Time = "2:00 PM"
                        },
                        new
                        {
                            AptId = 8,
                            Booked = false,
                            Day = "Monday",
                            Time = "2:00 PM"
                        },
                        new
                        {
                            AptId = 9,
                            Booked = false,
                            Day = "Monday",
                            Time = "3:00 PM"
                        },
                        new
                        {
                            AptId = 10,
                            Booked = false,
                            Day = "Monday",
                            Time = "4:00 PM"
                        },
                        new
                        {
                            AptId = 11,
                            Booked = false,
                            Day = "Monday",
                            Time = "5:00 PM"
                        },
                        new
                        {
                            AptId = 12,
                            Booked = false,
                            Day = "Monday",
                            Time = "6:00 PM"
                        },
                        new
                        {
                            AptId = 13,
                            Booked = false,
                            Day = "Monday",
                            Time = "7:00 PM"
                        },
                        new
                        {
                            AptId = 14,
                            Booked = false,
                            Day = "Monday",
                            Time = "8:00 PM"
                        },
                        new
                        {
                            AptId = 15,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "8:00 AM"
                        },
                        new
                        {
                            AptId = 16,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            AptId = 17,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            AptId = 18,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            AptId = 19,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "12:00 PM"
                        },
                        new
                        {
                            AptId = 20,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "1:00 PM"
                        },
                        new
                        {
                            AptId = 21,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "2:00 PM"
                        },
                        new
                        {
                            AptId = 22,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "2:00 PM"
                        },
                        new
                        {
                            AptId = 23,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "3:00 PM"
                        },
                        new
                        {
                            AptId = 24,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "4:00 PM"
                        },
                        new
                        {
                            AptId = 25,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "5:00 PM"
                        },
                        new
                        {
                            AptId = 26,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "6:00 PM"
                        },
                        new
                        {
                            AptId = 27,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "7:00 PM"
                        },
                        new
                        {
                            AptId = 28,
                            Booked = false,
                            Day = "Tuesday",
                            Time = "8:00 PM"
                        },
                        new
                        {
                            AptId = 29,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "8:00 AM"
                        },
                        new
                        {
                            AptId = 30,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            AptId = 31,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            AptId = 32,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            AptId = 33,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "12:00 PM"
                        },
                        new
                        {
                            AptId = 34,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "1:00 PM"
                        },
                        new
                        {
                            AptId = 35,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "2:00 PM"
                        },
                        new
                        {
                            AptId = 36,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "2:00 PM"
                        },
                        new
                        {
                            AptId = 37,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "3:00 PM"
                        },
                        new
                        {
                            AptId = 38,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "4:00 PM"
                        },
                        new
                        {
                            AptId = 39,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "5:00 PM"
                        },
                        new
                        {
                            AptId = 40,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "6:00 PM"
                        },
                        new
                        {
                            AptId = 41,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "7:00 PM"
                        },
                        new
                        {
                            AptId = 42,
                            Booked = false,
                            Day = "Wednesday",
                            Time = "8:00 PM"
                        },
                        new
                        {
                            AptId = 43,
                            Booked = false,
                            Day = "Thursday",
                            Time = "8:00 AM"
                        },
                        new
                        {
                            AptId = 44,
                            Booked = false,
                            Day = "Thursday",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            AptId = 45,
                            Booked = false,
                            Day = "Thursday",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            AptId = 46,
                            Booked = false,
                            Day = "Thursday",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            AptId = 47,
                            Booked = false,
                            Day = "Thursday",
                            Time = "12:00 PM"
                        },
                        new
                        {
                            AptId = 48,
                            Booked = false,
                            Day = "Thursday",
                            Time = "1:00 PM"
                        },
                        new
                        {
                            AptId = 49,
                            Booked = false,
                            Day = "Thursday",
                            Time = "2:00 PM"
                        },
                        new
                        {
                            AptId = 50,
                            Booked = false,
                            Day = "Thursday",
                            Time = "2:00 PM"
                        },
                        new
                        {
                            AptId = 51,
                            Booked = false,
                            Day = "Thursday",
                            Time = "3:00 PM"
                        },
                        new
                        {
                            AptId = 52,
                            Booked = false,
                            Day = "Thursday",
                            Time = "4:00 PM"
                        },
                        new
                        {
                            AptId = 53,
                            Booked = false,
                            Day = "Thursday",
                            Time = "5:00 PM"
                        },
                        new
                        {
                            AptId = 54,
                            Booked = false,
                            Day = "Thursday",
                            Time = "6:00 PM"
                        },
                        new
                        {
                            AptId = 55,
                            Booked = false,
                            Day = "Thursday",
                            Time = "7:00 PM"
                        },
                        new
                        {
                            AptId = 56,
                            Booked = false,
                            Day = "Thursday",
                            Time = "8:00 PM"
                        },
                        new
                        {
                            AptId = 57,
                            Booked = false,
                            Day = "Friday",
                            Time = "8:00 AM"
                        },
                        new
                        {
                            AptId = 58,
                            Booked = false,
                            Day = "Friday",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            AptId = 59,
                            Booked = false,
                            Day = "Friday",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            AptId = 60,
                            Booked = false,
                            Day = "Friday",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            AptId = 61,
                            Booked = false,
                            Day = "Friday",
                            Time = "12:00 PM"
                        },
                        new
                        {
                            AptId = 62,
                            Booked = false,
                            Day = "Friday",
                            Time = "1:00 PM"
                        },
                        new
                        {
                            AptId = 63,
                            Booked = false,
                            Day = "Friday",
                            Time = "2:00 PM"
                        },
                        new
                        {
                            AptId = 64,
                            Booked = false,
                            Day = "Friday",
                            Time = "2:00 PM"
                        },
                        new
                        {
                            AptId = 65,
                            Booked = false,
                            Day = "Friday",
                            Time = "3:00 PM"
                        },
                        new
                        {
                            AptId = 66,
                            Booked = false,
                            Day = "Friday",
                            Time = "4:00 PM"
                        },
                        new
                        {
                            AptId = 67,
                            Booked = false,
                            Day = "Friday",
                            Time = "5:00 PM"
                        },
                        new
                        {
                            AptId = 68,
                            Booked = false,
                            Day = "Friday",
                            Time = "6:00 PM"
                        },
                        new
                        {
                            AptId = 69,
                            Booked = false,
                            Day = "Friday",
                            Time = "7:00 PM"
                        },
                        new
                        {
                            AptId = 70,
                            Booked = false,
                            Day = "Friday",
                            Time = "8:00 PM"
                        },
                        new
                        {
                            AptId = 71,
                            Booked = false,
                            Day = "Saturday",
                            Time = "8:00 AM"
                        },
                        new
                        {
                            AptId = 72,
                            Booked = false,
                            Day = "Saturday",
                            Time = "9:00 AM"
                        },
                        new
                        {
                            AptId = 73,
                            Booked = false,
                            Day = "Saturday",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            AptId = 74,
                            Booked = false,
                            Day = "Saturday",
                            Time = "11:00 AM"
                        },
                        new
                        {
                            AptId = 75,
                            Booked = false,
                            Day = "Saturday",
                            Time = "12:00 PM"
                        },
                        new
                        {
                            AptId = 76,
                            Booked = false,
                            Day = "Saturday",
                            Time = "1:00 PM"
                        },
                        new
                        {
                            AptId = 77,
                            Booked = false,
                            Day = "Saturday",
                            Time = "2:00 PM"
                        },
                        new
                        {
                            AptId = 78,
                            Booked = false,
                            Day = "Saturday",
                            Time = "2:00 PM"
                        },
                        new
                        {
                            AptId = 79,
                            Booked = false,
                            Day = "Saturday",
                            Time = "3:00 PM"
                        },
                        new
                        {
                            AptId = 80,
                            Booked = false,
                            Day = "Saturday",
                            Time = "4:00 PM"
                        },
                        new
                        {
                            AptId = 81,
                            Booked = false,
                            Day = "Saturday",
                            Time = "5:00 PM"
                        },
                        new
                        {
                            AptId = 82,
                            Booked = false,
                            Day = "Saturday",
                            Time = "6:00 PM"
                        },
                        new
                        {
                            AptId = 83,
                            Booked = false,
                            Day = "Saturday",
                            Time = "7:00 PM"
                        },
                        new
                        {
                            AptId = 84,
                            Booked = false,
                            Day = "Saturday",
                            Time = "8:00 PM"
                        });
                });

            modelBuilder.Entity("Mission12.Models.Booking", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Day")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("BookID");

                    b.ToTable("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
